/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { Daonation } from "./Daonation";
export type { DaonationToken } from "./DaonationToken";
export type { IDaonation } from "./IDaonation";
